[project]
name = "call_me_maybe"
version = "0.1.0"
description = "Codam Core Curriculum: Call Me Maybe"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "mypy>=2.3.0",
  "numpy>=2.5.1",
  "pydantic>=2.13.4",
  "torch>=2.13.0",        # required at runtime by llm_sdk, never used in src code
  "transformers>=5.14.1", # ditto
]

[[tool.mypy.overrides]]
module = "llm_sdk.*"
ignore_errors = true

[tool.mypy]
explicit_package_bases = true
mypy_path = "."
